---
name: "ManjaroWSL2 - Bug Report"
description: Report a bug on ManjaroWSL2
body:
- type: markdown
  attributes:
    value: |
      Please [search for existing issues](https://github.com/sileshn/ManjaroWSL2/issues) before creating a new one.
      
- type: checkboxes
  attributes:
    label: Requirements
    description: |
      Tell us whether you have checked and completed the [prerequisite](https://github.com/sileshn/ManjaroWSL2#requirements)
    options:
      - label: "Yes"
      - label: "No"
      
- type: checkboxes
  attributes:
    label: WSL Version
    description: |
      Tell us whether you are running WSL 2 and/or WSL 1. You can tell your WSL version by running `wsl -l -v`. ManjaroWSL2 needs wsl2 to work.
    options:
      - label: "WSL 2"
      - label: "WSL 1"
    
- type: input
  attributes:
    label: Windows Build Number
    description: |
      Please run `cmd.exe /c ver` to get the build of Windows you are on.
    placeholder: "Microsoft Windows [Version 10.0.19042.867]"
  validations:
    required: true

- type: input
  attributes:
    label: Kernel Version
    description: |
      Please tell us what version of the Linux kernel you are using, or if you are using a custom kernel. 
      You can run `wsl.exe --status` if that command is available to you, or by running `cat /proc/version` in your distro.
    placeholder: "5.4.72"
  validations:
    required: false

- type: textarea
  attributes:
    label: Repro Steps
    description: Please list out the steps to reproduce your bug.  
    placeholder: Your steps go here. Include relevant environmental variables or any other configuration.
  validations:
    required: true

- type: textarea
  attributes:
    label: Expected Behavior
    description: What were you expecting to see? Include any relevant examples or documentation links.
    placeholder: If you want to include screenshots, paste them into the text area or follow up with a separate comment. 
  validations:
    required: true

- type: textarea
  attributes:
    label: Actual Behavior
    description: What happened instead?
    placeholder: Include the terminal output, straces of the failing command, etc. as necessary.
  validations:
    required: true