name: Build and Release

on:
  # Se ejecuta automáticamente el primer día de cada mes a las 00:00 UTC
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      release_date: ${{ steps.set_date.outputs.DATE }}
    container:
      image: klozzjesus/aosp_orangefox-builder:latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set date
        id: set_date
        run: |
          DATE=$(date +'%Y%m%d')
          echo "DATE=$DATE" >> $GITHUB_OUTPUT
          echo "DATE=$DATE" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          sudo pacman -Syuu  --noconfirm
          sudo pacman -Syu --noconfirm zip make tar libarchive docker jq curl unzip

      - name: Build project
        run: |
          make clean
          make

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ManjaroWSL2
          path: ManjaroWSL2.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ManjaroWSL2

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ManjaroWSL2.zip
          tag_name: ${{ needs.build.outputs.release_date }}
          name: ManjaroWSL2-${{ needs.build.outputs.release_date }}
          body: "ManjaroWSL2 Monthly Automatic Release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
